language: node_js
node_js:
  - "6"
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
 - export PORT=8000
 - npm start & sleep 3
 - psql -c 'create database test_twitter;' -U postgres -w
 - psql -f 'testdatabasescript.sql'
